// ==========================================
// SISTEM BAHASA OTOMATIS SESUAI NEGARA
// Tambahkan/ubah bahasa di sini saja
// ==========================================

const terjemahan = {
    // 🇮🇩 Indonesia
    ID: {
        selamatDatang: 'Masuk ke Amazon',
        emailLabel: 'Email atau nomor ponsel',
        lanjut: 'Lanjutkan',
        syarat: 'Dengan melanjutkan, Anda menyetujui Ketentuan Penggunaan dan Pemberitahuan Privasi Amazon.',
        butuhBantuan: 'Butuh bantuan?',
        beliKerja: 'Berbelanja untuk keperluan kerja?',
        tokoBisnis: 'Berbelanja di Amazon Bisnis',
        baruAmazon: 'Baru di Amazon?',
        buatAkun: 'Buat akun Amazon Anda',
        kataSandi: 'Kata Sandi',
        masuk: 'Masuk',
        masukKunci: 'Masuk dengan kunci sandi',
        ganti: 'Ubah',
        tahanAkun: 'Akun ditangguhkan sementara',
        peringatan: 'Kami mendeteksi aktivitas pembayaran yang tidak biasa dan perlu memverifikasi kepemilikan metode pembayaran.',
        konfirmasiIdentitas: 'Konfirmasi identitas Anda',
        masukkanInfo: 'Masukkan informasi yang sesuai dengan akun Anda.',
        negaraWilayah: 'Negara/Wilayah',
        namaLengkap: 'Nama Lengkap',
        ttl: 'Tanggal Lahir',
        nomorHP: 'Nomor Ponsel',
        alamat1: 'Alamat Baris 1',
        alamat2: 'Alamat Baris 2',
        kota: 'Kota',
        provinsi: 'Provinsi',
        kodePos: 'Kode Pos',
        alamatBawaan: 'Jadikan ini alamat saya yang utama',
        verifikasiAlamat: 'Verifikasi Alamat',
        kirimBerhasil: 'Data telah dikirim!',
        kembaliAtas: 'Kembali ke atas',
        akunSaya: 'Akun Saya',
        pesanan: 'Pesanan',
        keranjang: 'Keranjang',
        selamat: 'Halo, Masuk'
    },

    // 🇺🇸 United States / 🇬🇧 United Kingdom
    US: {
        selamatDatang: 'Sign In',
        emailLabel: 'Email or mobile phone number',
        lanjut: 'Continue',
        syarat: 'By continuing, you agree to Amazon\'s Conditions of Use and Privacy Notice.',
        butuhBantuan: 'Need help?',
        beliKerja: 'Buying for work?',
        tokoBisnis: 'Shop on Amazon Business',
        baruAmazon: 'New to Amazon?',
        buatAkun: 'Create your Amazon account',
        kataSandi: 'Password',
        masuk: 'Sign in',
        masukKunci: 'Sign in with a passkey',
        ganti: 'Change',
        tahanAkun: 'Account on hold temporarily',
        peringatan: 'We notice unusual payment activity on your account and need to verify ownership of the payment method used on your most recent order.',
        konfirmasiIdentitas: 'Confirm your identity',
        masukkanInfo: 'Please enter the information that matches your account.',
        negaraWilayah: 'Country/Region',
        namaLengkap: 'Full name (First and Last name)',
        ttl: 'Date of Birth',
        nomorHP: 'Phone number',
        alamat1: 'Address line 1',
        alamat2: 'Address line 2',
        kota: 'City',
        provinsi: 'State',
        kodePos: 'ZIP Code',
        alamatBawaan: 'This is my default address',
        verifikasiAlamat: 'Verify Address',
        kirimBerhasil: 'Data has been sent!',
        kembaliAtas: 'Back to top',
        akunSaya: 'Your Account',
        pesanan: 'Returns & Orders',
        keranjang: 'Cart',
        selamat: 'Hello, Sign in'
    },

    // 🇦🇺 Australia
    AU: {
        selamatDatang: 'Sign In',
        emailLabel: 'Email or mobile phone number',
        lanjut: 'Continue',
        syarat: 'By continuing, you agree to Amazon\'s Conditions of Use and Privacy Notice.',
        butuhBantuan: 'Need help?',
        beliKerja: 'Buying for work?',
        tokoBisnis: 'Shop on Amazon Business',
        baruAmazon: 'New to Amazon?',
        buatAkun: 'Create your Amazon account',
        kataSandi: 'Password',
        masuk: 'Sign in',
        masukKunci: 'Sign in with a passkey',
        ganti: 'Change',
        tahanAkun: 'Account on hold temporarily',
        peringatan: 'We noticed unusual activity — please verify your details.',
        konfirmasiIdentitas: 'Confirm your identity',
        masukkanInfo: 'Enter your details exactly as they appear on your account.',
        negaraWilayah: 'Country/Region',
        namaLengkap: 'Full name',
        ttl: 'Date of Birth',
        nomorHP: 'Phone number',
        alamat1: 'Street address',
        alamat2: 'Apartment, suite, unit (optional)',
        kota: 'Suburb/City',
        provinsi: 'State/Territory',
        kodePos: 'Postcode',
        alamatBawaan: 'Set as default address',
        verifikasiAlamat: 'Verify Address',
        kirimBerhasil: 'Information submitted successfully!',
        kembaliAtas: 'Back to top',
        akunSaya: 'Your Account',
        pesanan: 'Returns & Orders',
        keranjang: 'Cart',
        selamat: 'Hello, Sign in'
    },

    // 🇸🇬 Singapore
    SG: {
        selamatDatang: 'Sign In',
        emailLabel: 'Email or mobile number',
        lanjut: 'Continue',
        syarat: 'By continuing, you agree to Amazon\'s Conditions of Use and Privacy Notice.',
        butuhBantuan: 'Need help?',
        beliKerja: 'Shopping for work?',
        tokoBisnis: 'Shop Amazon Business',
        baruAmazon: 'New to Amazon?',
        buatAkun: 'Create your Amazon account',
        kataSandi: 'Password',
        masuk: 'Sign in',
        masukKunci: 'Sign in with passkey',
        ganti: 'Change',
        tahanAkun: 'Account verification required',
        peringatan: 'To ensure your account security, please verify your identity.',
        konfirmasiIdentitas: 'Verify your identity',
        masukkanInfo: 'Enter information matching your account records.',
        negaraWilayah: 'Country/Region',
        namaLengkap: 'Full name',
        ttl: 'Date of Birth',
        nomorHP: 'Mobile number',
        alamat1: 'Block / Street address',
        alamat2: 'Unit / Building',
        kota: 'City',
        provinsi: 'State/Province',
        kodePos: 'Postal Code',
        alamatBawaan: 'Set as default address',
        verifikasiAlamat: 'Verify Now',
        kirimBerhasil: 'Verification submitted!',
        kembaliAtas: 'Back to top',
        akunSaya: 'Your Account',
        pesanan: 'Returns & Orders',
        keranjang: 'Cart',
        selamat: 'Hello, Sign in'
    },

    // 🇲🇾 Malaysia
    MY: {
        selamatDatang: 'Log Masuk',
        emailLabel: 'E-mel atau nombor telefon',
        lanjut: 'Teruskan',
        syarat: 'Dengan meneruskan, anda bersetuju dengan Syarat Penggunaan dan Notis Privasi Amazon.',
        butuhBantuan: 'Perlukan bantuan?',
        beliKerja: 'Membeli untuk kerja?',
        tokoBisnis: 'Belanja di Amazon Perniagaan',
        baruAmazon: 'Baru di Amazon?',
        buatAkun: 'Cipta akaun Amazon anda',
        kataSandi: 'Kata Laluan',
        masuk: 'Log Masuk',
        masukKunci: 'Log masuk dengan kunci laluan',
        ganti: 'Tukar',
        tahanAkun: 'Akun sedang disemak',
        peringatan: 'Kami mengesan aktiviti luar biasa. Sila sahkan butiran anda.',
        konfirmasiIdentitas: 'Sahkan identiti anda',
        masukkanInfo: 'Masukkan maklumat yang sepadan dengan akaun anda.',
        negaraWilayah: 'Negara/Kawasan',
        namaLengkap: 'Nama Penuh',
        ttl: 'Tarikh Lahir',
        nomorHP: 'Nombor Telefon',
        alamat1: 'Alamat Baris 1',
        alamat2: 'Alamat Baris 2',
        kota: 'Bandar',
        provinsi: 'Negeri',
        kodePos: 'Poskod',
        alamatBawaan: 'Jadikan alamat utama',
        verifikasiAlamat: 'Sahkan Alamat',
        kirimBerhasil: 'Maklumat telah dihantar!',
        kembaliAtas: 'Kembali ke atas',
        akunSaya: 'Akaun Saya',
        pesanan: 'Pulangan & Pesanan',
        keranjang: 'Troli',
        selamat: 'Hai, Log Masuk'
    }
};

// Bahasa utama jika negara belum tersedia → pakai Bahasa Inggris
const BAHASA_BAWAAN = 'US';

// Fungsi ambil teks sesuai kode negara
function teks(kodeNegara, kunci) {
    const bhs = terjemahan[kodeNegara] || terjemahan[BAHASA_BAWAAN];
    return bhs[kunci] || terjemahan[BAHASA_BAWAAN][kunci] || kunci;
}
