// ==========================================
// DAFTAR NEGARA LENGKAP A–Z
// Tidak perlu mengubah bagian lain, cukup di sini
// ==========================================

const daftarNegara = {
    AF: { nama: 'Afghanistan', bendera: '🇦🇫' },
    AL: { nama: 'Albania', bendera: '🇦🇱' },
    DZ: { nama: 'Algeria', bendera: '🇩🇿' },
    AS: { nama: 'American Samoa', bendera: '🇦🇸' },
    AD: { nama: 'Andorra', bendera: '🇦🇩' },
    AO: { nama: 'Angola', bendera: '🇦🇴' },
    AI: { nama: 'Anguilla', bendera: '🇦🇮' },
    AG: { nama: 'Antigua and Barbuda', bendera: '🇦🇬' },
    AR: { nama: 'Argentina', bendera: '🇦🇷' },
    AM: { nama: 'Armenia', bendera: '🇦🇲' },
    AW: { nama: 'Aruba', bendera: '🇦🇼' },
    AU: { nama: 'Australia', bendera: '🇦🇺' },
    AT: { nama: 'Austria', bendera: '🇦🇹' },
    AZ: { nama: 'Azerbaijan', bendera: '🇦🇿' },
    BS: { nama: 'Bahamas', bendera: '🇧🇸' },
    BH: { nama: 'Bahrain', bendera: '🇧🇭' },
    BD: { nama: 'Bangladesh', bendera: '🇧🇩' },
    BB: { nama: 'Barbados', bendera: '🇧🇧' },
    BY: { nama: 'Belarus', bendera: '🇧🇾' },
    BE: { nama: 'Belgium', bendera: '🇧🇪' },
    BZ: { nama: 'Belize', bendera: '🇧🇿' },
    BJ: { nama: 'Benin', bendera: '🇧🇯' },
    BM: { nama: 'Bermuda', bendera: '🇧🇲' },
    BT: { nama: 'Bhutan', bendera: '🇧🇹' },
    BO: { nama: 'Bolivia', bendera: '🇧🇴' },
    BA: { nama: 'Bosnia and Herzegovina', bendera: '🇧🇦' },
    BW: { nama: 'Botswana', bendera: '🇧🇼' },
    BR: { nama: 'Brazil', bendera: '🇧🇷' },
    BN: { nama: 'Brunei Darussalam', bendera: '🇧🇳' },
    BG: { nama: 'Bulgaria', bendera: '🇧🇬' },
    BF: { nama: 'Burkina Faso', bendera: '🇧🇫' },
    BI: { nama: 'Burundi', bendera: '🇧🇮' },
    KH: { nama: 'Cambodia', bendera: '🇰🇭' },
    CM: { nama: 'Cameroon', bendera: '🇨🇲' },
    CA: { nama: 'Canada', bendera: '🇨🇦' },
    CV: { nama: 'Cape Verde', bendera: '🇨🇻' },
    KY: { nama: 'Cayman Islands', bendera: '🇰🇾' },
    CF: { nama: 'Central African Republic', bendera: '🇨🇫' },
    TD: { nama: 'Chad', bendera: '🇹🇩' },
    CL: { nama: 'Chile', bendera: '🇨🇱' },
    CN: { nama: 'China', bendera: '🇨🇳' },
    CO: { nama: 'Colombia', bendera: '🇨🇴' },
    KM: { nama: 'Comoros', bendera: '🇰🇲' },
    CG: { nama: 'Congo', bendera: '🇨🇬' },
    CD: { nama: 'Congo, DR', bendera: '🇨🇩' },
    CR: { nama: 'Costa Rica', bendera: '🇨🇷' },
    CI: { nama: "Côte d'Ivoire", bendera: '🇨🇮' },
    HR: { nama: 'Croatia', bendera: '🇭🇷' },
    CU: { nama: 'Cuba', bendera: '🇨🇺' },
    CY: { nama: 'Cyprus', bendera: '🇨🇾' },
    CZ: { nama: 'Czech Republic', bendera: '🇨🇿' },
    DK: { nama: 'Denmark', bendera: '🇩🇰' },
    DJ: { nama: 'Djibouti', bendera: '🇩🇯' },
    DM: { nama: 'Dominica', bendera: '🇩🇲' },
    DO: { nama: 'Dominican Republic', bendera: '🇩🇴' },
    EC: { nama: 'Ecuador', bendera: '🇪🇨' },
    EG: { nama: 'Egypt', bendera: '🇪🇬' },
    SV: { nama: 'El Salvador', bendera: '🇸🇻' },
    GQ: { nama: 'Equatorial Guinea', bendera: '🇬🇶' },
    ER: { nama: 'Eritrea', bendera: '🇪🇷' },
    EE: { nama: 'Estonia', bendera: '🇪🇪' },
    ET: { nama: 'Ethiopia', bendera: '🇪🇹' },
    FJ: { nama: 'Fiji', bendera: '🇫🇯' },
    FI: { nama: 'Finland', bendera: '🇫🇮' },
    FR: { nama: 'France', bendera: '🇫🇷' },
    GA: { nama: 'Gabon', bendera: '🇬🇦' },
    GM: { nama: 'Gambia', bendera: '🇬🇲' },
    GE: { nama: 'Georgia', bendera: '🇬🇪' },
    DE: { nama: 'Germany', bendera: '🇩🇪' },
    GH: { nama: 'Ghana', bendera: '🇬🇭' },
    GR: { nama: 'Greece', bendera: '🇬🇷' },
    GL: { nama: 'Greenland', bendera: '🇬🇱' },
    GD: { nama: 'Grenada', bendera: '🇬🇩' },
    GT: { nama: 'Guatemala', bendera: '🇬🇹' },
    GN: { nama: 'Guinea', bendera: '🇬🇳' },
    GW: { nama: 'Guinea-Bissau', bendera: '🇬🇼' },
    GY: { nama: 'Guyana', bendera: '🇬🇾' },
    HT: { nama: 'Haiti', bendera: '🇭🇹' },
    HN: { nama: 'Honduras', bendera: '🇭🇳' },
    HK: { nama: 'Hong Kong', bendera: '🇭🇰' },
    HU: { nama: 'Hungary', bendera: '🇭🇺' },
    IS: { nama: 'Iceland', bendera: '🇮🇸' },
    IN: { nama: 'India', bendera: '🇮🇳' },
    ID: { nama: 'Indonesia', bendera: '🇮🇩' },
    IR: { nama: 'Iran', bendera: '🇮🇷' },
    IQ: { nama: 'Iraq', bendera: '🇮🇶' },
    IE: { nama: 'Ireland', bendera: '🇮🇪' },
    IL: { nama: 'Israel', bendera: '🇮🇱' },
    IT: { nama: 'Italy', bendera: '🇮🇹' },
    JM: { nama: 'Jamaica', bendera: '🇯🇲' },
    JP: { nama: 'Japan', bendera: '🇯🇵' },
    JO: { nama: 'Jordan', bendera: '🇯🇴' },
    KZ: { nama: 'Kazakhstan', bendera: '🇰🇿' },
    KE: { nama: 'Kenya', bendera: '🇰🇪' },
    KI: { nama: 'Kiribati', bendera: '🇰🇮' },
    KW: { nama: 'Kuwait', bendera: '🇰🇼' },
    KG: { nama: 'Kyrgyzstan', bendera: '🇰🇬' },
    LA: { nama: 'Laos', bendera: '🇱🇦' },
    LV: { nama: 'Latvia', bendera: '🇱🇻' },
    LB: { nama: 'Lebanon', bendera: '🇱🇧' },
    LS: { nama: 'Lesotho', bendera: '🇱🇸' },
    LR: { nama: 'Liberia', bendera: '🇱🇷' },
    LY: { nama: 'Libya', bendera: '🇱🇾' },
    LI: { nama: 'Liechtenstein', bendera: '🇱🇮' },
    LT: { nama: 'Lithuania', bendera: '🇱🇹' },
    LU: { nama: 'Luxembourg', bendera: '🇱🇺' },
    MO: { nama: 'Macao', bendera: '🇲🇴' },
    MK: { nama: 'North Macedonia', bendera: '🇲🇰' },
    MG: { nama: 'Madagascar', bendera: '🇲🇬' },
    MW: { nama: 'Malawi', bendera: '🇲🇼' },
    MY: { nama: 'Malaysia', bendera: '🇲🇾' },
    MV: { nama: 'Maldives', bendera: '🇲🇻' },
    ML: { nama: 'Mali', bendera: '🇲🇱' },
    MT: { nama: 'Malta', bendera: '🇲🇹' },
    MQ: { nama: 'Martinique', bendera: '🇲🇶' },
    MR: { nama: 'Mauritania', bendera: '🇲🇷' },
    MU: { nama: 'Mauritius', bendera: '🇲🇺' },
    MX: { nama: 'Mexico', bendera: '🇲🇽' },
    FM: { nama: 'Micronesia', bendera: '🇫🇲' },
    MD: { nama: 'Moldova', bendera: '🇲🇩' },
    MC: { nama: 'Monaco', bendera: '🇲🇨' },
    MN: { nama: 'Mongolia', bendera: '🇲🇳' },
    ME: { nama: 'Montenegro', bendera: '🇲🇪' },
    MA: { nama: 'Morocco', bendera: '🇲🇦' },
    MZ: { nama: 'Mozambique', bendera: '🇲🇿' },
    MM: { nama: 'Myanmar', bendera: '🇲🇲' },
    NA: { nama: 'Namibia', bendera: '🇳🇦' },
    NR: { nama: 'Nauru', bendera: '🇳🇷' },
    NP: { nama: 'Nepal', bendera: '🇳🇵' },
    NL: { nama: 'Netherlands', bendera: '🇳🇱' },
    NZ: { nama: 'New Zealand', bendera: '🇳🇿' },
    NI: { nama: 'Nicaragua', bendera: '🇳🇮' },
    NE: { nama: 'Niger', bendera: '🇳🇪' },
    NG: { nama: 'Nigeria', bendera: '🇳🇬' },
    KP: { nama: 'North Korea', bendera: '🇰🇵' },
    NO: { nama: 'Norway', bendera: '🇳🇴' },
    OM: { nama: 'Oman', bendera: '🇴🇲' },
    PK: { nama: 'Pakistan', bendera: '🇵🇰' },
    PW: { nama: 'Palau', bendera: '🇵🇼' },
    PA: { nama: 'Panama', bendera: '🇵🇦' },
    PG: { nama: 'Papua New Guinea', bendera: '🇵🇬' },
    PY: { nama: 'Paraguay', bendera: '🇵🇾' },
    PE: { nama: 'Peru', bendera: '🇵🇪' },
    PH: { nama: 'Philippines', bendera: '🇵🇭' },
    PL: { nama: 'Poland', bendera: '🇵🇱' },
    PT: { nama: 'Portugal', bendera: '🇵🇹' },
    QA: { nama: 'Qatar', bendera: '🇶🇦' },
    KR: { nama: 'South Korea', bendera: '🇰🇷' },
    RO: { nama: 'Romania', bendera: '🇷🇴' },
    RU: { nama: 'Russia', bendera: '🇷🇺' },
    RW: { nama: 'Rwanda', bendera: '🇷🇼' },
    SA: { nama: 'Saudi Arabia', bendera: '🇸🇦' },
    SN: { nama: 'Senegal', bendera: '🇸🇳' },
    RS: { nama: 'Serbia', bendera: '🇷🇸' },
    SG: { nama: 'Singapore', bendera: '🇸🇬' },
    SK: { nama: 'Slovakia', bendera: '🇸🇰' },
    SI: { nama: 'Slovenia', bendera: '🇸🇮' },
    SO: { nama: 'Somalia', bendera: '🇸🇴' },
    ZA: { nama: 'South Africa', bendera: '🇿🇦' },
    ES: { nama: 'Spain', bendera: '🇪🇸' },
    LK: { nama: 'Sri Lanka', bendera: '🇱🇰' },
    SD: { nama: 'Sudan', bendera: '🇸🇩' },
    SE: { nama: 'Sweden', bendera: '🇸🇪' },
    CH: { nama: 'Switzerland', bendera: '🇨🇭' },
    SY: { nama: 'Syria', bendera: '🇸🇾' },
    TW: { nama: 'Taiwan', bendera: '🇹🇼' },
    TJ: { nama: 'Tajikistan', bendera: '🇹🇯' },
    TZ: { nama: 'Tanzania', bendera: '🇹🇿' },
    TH: { nama: 'Thailand', bendera: '🇹🇭' },
    TG: { nama: 'Togo', bendera: '🇹🇬' },
    TN: { nama: 'Tunisia', bendera: '🇹🇳' },
    TR: { nama: 'Turkey', bendera: '🇹🇷' },
    TM: { nama: 'Turkmenistan', bendera: '🇹🇲' },
    UG: { nama: 'Uganda', bendera: '🇺🇬' },
    UA: { nama: 'Ukraine', bendera: '🇺🇦' },
    AE: { nama: 'United Arab Emirates', bendera: '🇦🇪' },
    GB: { nama: 'United Kingdom', bendera: '🇬🇧' },
    US: { nama: 'United States', bendera: '🇺🇸' },
    UY: { nama: 'Uruguay', bendera: '🇺🇾' },
    UZ: { nama: 'Uzbekistan', bendera: '🇺🇿' },
    VU: { nama: 'Vanuatu', bendera: '🇻🇺' },
    VE: { nama: 'Venezuela', bendera: '🇻🇪' },
    VN: { nama: 'Vietnam', bendera: '🇻🇳' },
    YE: { nama: 'Yemen', bendera: '🇾🇪' },
    ZM: { nama: 'Zambia', bendera: '🇿🇲' },
    ZW: { nama: 'Zimbabwe', bendera: '🇿🇼' }
};

// Tetapan jika negara tidak terdeteksi
const NEGARA_BAWAAN = { nama: 'United States', bendera: '🇺🇸' };